#!/usr/bin/env bash
# =============================================================================
# OpenClaw + Telegram — VPS Install Script
# Tested on: Ubuntu 22.04 / 24.04
# Usage:  bash install-openclaw.sh
# =============================================================================

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }

# ── Helpers ───────────────────────────────────────────────────────────────────
require_root() {
  [[ $EUID -eq 0 ]] || error "Run this script as root: sudo bash $0"
}

check_os() {
  . /etc/os-release 2>/dev/null || error "Cannot detect OS."
  [[ "$ID" == "ubuntu" || "$ID" == "debian" ]] \
    || warn "Untested OS: $ID. Proceeding anyway."
}

prompt() {
  local var="$1" msg="$2" default="${3:-}"
  if [[ -n "$default" ]]; then
    read -rp "$(echo -e "${BOLD}$msg${RESET} [${default}]: ")" val
    printf -v "$var" '%s' "${val:-$default}"
  else
    read -rp "$(echo -e "${BOLD}$msg${RESET}: ")" val
    [[ -n "$val" ]] || error "$msg is required."
    printf -v "$var" '%s' "$val"
  fi
}

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}${CYAN}"
cat << 'EOF'
  ___                   ____ _
 / _ \ _ __   ___ _ __ / ___| | __ ___      __
| | | | '_ \ / _ \ '_ \ |   | |/ _` \ \ /\ / /
| |_| | |_) |  __/ | | | |___| | (_| |\ V  V /
 \___/| .__/ \___|_| |_|\____|_|\__,_| \_/\_/  + Telegram
      |_|
EOF
echo -e "${RESET}"

# ── Pre-checks ────────────────────────────────────────────────────────────────
require_root
check_os

# ── Gather config ─────────────────────────────────────────────────────────────
echo -e "\n${BOLD}--- Configuration ---${RESET}"
prompt TELEGRAM_TOKEN  "Telegram Bot Token (from @BotFather)"
prompt DM_POLICY       "dmPolicy — who can DM the bot (pairing/open)" "pairing"
prompt LLM_PROVIDER    "LLM provider (anthropic/openai/google)"       "anthropic"
prompt LLM_API_KEY     "LLM API Key"
prompt OPENCLAW_DIR    "OpenClaw data directory"                      "/opt/openclaw"

echo ""
info "Settings:"
echo "  Bot token  : ${TELEGRAM_TOKEN:0:10}... (truncated)"
echo "  dmPolicy   : $DM_POLICY"
echo "  LLM        : $LLM_PROVIDER"
echo "  Data dir   : $OPENCLAW_DIR"
echo ""
read -rp "Proceed with install? [y/N] " confirm
[[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }

# ── Step 1: System packages ───────────────────────────────────────────────────
echo -e "\n${BOLD}[1/5] Installing system packages...${RESET}"
apt-get update -qq
apt-get install -y -qq curl ca-certificates ufw
success "System packages ready."

# ── Step 2: Docker ───────────────────────────────────────────────────────────
echo -e "\n${BOLD}[2/5] Installing Docker...${RESET}"
if command -v docker &>/dev/null; then
  success "Docker already installed: $(docker --version)"
else
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
  success "Docker installed: $(docker --version)"
fi

# ── Step 3: Firewall ─────────────────────────────────────────────────────────
echo -e "\n${BOLD}[3/5] Configuring firewall...${RESET}"
ufw --force reset > /dev/null
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw limit 22/tcp         # rate-limit SSH (brute-force protection)
ufw --force enable
success "Firewall active — only SSH open."

# ── Step 4: OpenClaw config ──────────────────────────────────────────────────
echo -e "\n${BOLD}[4/5] Writing OpenClaw config...${RESET}"
mkdir -p "$OPENCLAW_DIR/data"

cat > "$OPENCLAW_DIR/docker-compose.yml" << COMPOSE
services:
  openclaw:
    image: ghcr.io/openclaw/openclaw:latest
    container_name: openclaw-gateway
    restart: always
    ports:
      - "127.0.0.1:18789:18789"
    volumes:
      - $OPENCLAW_DIR/data:/home/node/.openclaw
    environment:
      - NODE_ENV=production
COMPOSE

cat > "$OPENCLAW_DIR/data/config.json5" << CONFIG
{
  // OpenClaw configuration — generated by install-openclaw.sh
  "channels": {
    "telegram": {
      "enabled": true,
      "botToken": "$TELEGRAM_TOKEN",
      "dmPolicy": "$DM_POLICY"
    }
  },
  "llm": {
    "provider": "$LLM_PROVIDER",
    "apiKey": "$LLM_API_KEY"
  }
}
CONFIG

chmod 600 "$OPENCLAW_DIR/data/config.json5"   # protect secrets
success "Config written to $OPENCLAW_DIR/data/config.json5"

# ── Step 5: Launch ───────────────────────────────────────────────────────────
echo -e "\n${BOLD}[5/5] Starting OpenClaw...${RESET}"
cd "$OPENCLAW_DIR"
docker compose pull -q
docker compose up -d

# Wait for container to initialise
sleep 5

if docker compose ps | grep -q "Up"; then
  success "OpenClaw is running!"
else
  error "Container failed to start. Run: docker compose -f $OPENCLAW_DIR/docker-compose.yml logs"
fi

# ── Token retrieval ───────────────────────────────────────────────────────────
GATEWAY_TOKEN=""
for i in {1..10}; do
  GATEWAY_TOKEN=$(cat "$OPENCLAW_DIR/data/openclaw.json" 2>/dev/null \
    | grep -o '"token":"[^"]*"' | cut -d'"' -f4 || true)
  [[ -n "$GATEWAY_TOKEN" ]] && break
  sleep 2
done

# ── Summary ───────────────────────────────────────────────────────────────────
echo -e "\n${GREEN}${BOLD}=== Install Complete ===${RESET}"
echo ""
echo -e "  Gateway URL  : ${CYAN}http://127.0.0.1:18789${RESET}"
if [[ -n "$GATEWAY_TOKEN" ]]; then
  echo -e "  Gateway token: ${CYAN}$GATEWAY_TOKEN${RESET}"
  echo -e "  Direct URL   : ${CYAN}http://127.0.0.1:18789/?token=$GATEWAY_TOKEN${RESET}"
else
  warn "Token not yet written — check in a few seconds:"
  echo "  cat $OPENCLAW_DIR/data/openclaw.json | grep token"
fi
echo ""
echo -e "${BOLD}--- Next steps ---${RESET}"
echo "  1. SSH tunnel to access UI locally:"
echo "     ssh -L 18789:127.0.0.1:18789 root@YOUR_VPS_IP"
echo ""
echo "  2. Message your Telegram bot — it will send a pairing code."
echo ""
echo "  3. Approve the user on this server:"
echo "     docker exec openclaw-gateway openclaw pairing list telegram"
echo "     docker exec openclaw-gateway openclaw pairing approve telegram"
echo ""
echo "  4. To view logs:"
echo "     docker compose -f $OPENCLAW_DIR/docker-compose.yml logs -f"
echo ""
echo -e "${YELLOW}Security reminder:${RESET} Your config file contains secrets."
echo "  Location: $OPENCLAW_DIR/data/config.json5 (chmod 600)"
