"""
Smart contract generator core.

Entry point: generate(contract_type, params) -> str
"""

SUPPORTED_TYPES = ["erc20", "erc721", "multisig"]


def generate(contract_type: str, params: dict) -> str:
    """
    Generate a smart contract scaffold for the given type and parameters.

    Args:
        contract_type: One of SUPPORTED_TYPES.
        params: Dict of contract-specific fields (e.g. name, symbol, owner).

    Returns:
        A string containing the generated contract source.

    Raises:
        ValueError: If contract_type is not supported.
    """
    contract_type = contract_type.lower().strip()
    if contract_type not in SUPPORTED_TYPES:
        raise ValueError(
            f"Unsupported contract type '{contract_type}'. "
            f"Choose from: {', '.join(SUPPORTED_TYPES)}"
        )

    name = params.get("name", "MyContract")

    # TODO: replace stubs with real template rendering per contract type
    return (
        f"// SPDX-License-Identifier: MIT\n"
        f"pragma solidity ^0.8.0;\n\n"
        f"// [{contract_type.upper()}] {name}\n"
        f"// Generated by smart-contract-generator\n"
        f"// TODO: implement {contract_type} logic\n"
        f"contract {name} {{\n"
        f"    // constructor and methods go here\n"
        f"}}\n"
    )
