"""
Smart contract generator core.

Entry point: generate(contract_type, params) -> str
"""

SUPPORTED_TYPES = ["erc20", "erc721", "multisig"]

# Fields required per contract type. None values are also rejected.
REQUIRED_PARAMS: dict[str, list[str]] = {
    "erc20": ["name"],
    "erc721": ["name"],
    "multisig": ["name"],
}


def _validate_params(contract_type: str, params: dict) -> None:
    """Raise ValueError if any required param is missing or None."""
    for field in REQUIRED_PARAMS.get(contract_type, []):
        if params.get(field) is None:
            raise ValueError(
                f"Missing required param '{field}' for contract type '{contract_type}'."
            )


def generate(contract_type: str, params: dict) -> str:
    """
    Generate a smart contract scaffold for the given type and parameters.

    Args:
        contract_type: One of SUPPORTED_TYPES.
        params: Dict of contract-specific fields (e.g. name, symbol, owner).

    Returns:
        A string containing the generated contract source.

    Raises:
        ValueError: If contract_type is not supported or required params are missing.
    """
    contract_type = contract_type.lower().strip()
    if contract_type not in SUPPORTED_TYPES:
        raise ValueError(
            f"Unsupported contract type '{contract_type}'. "
            f"Choose from: {', '.join(SUPPORTED_TYPES)}"
        )

    _validate_params(contract_type, params)

    name = params.get("name", "MyContract")

    # TODO: replace stubs with real template rendering per contract type
    return (
        f"// SPDX-License-Identifier: MIT\n"
        f"pragma solidity ^0.8.0;\n\n"
        f"// [{contract_type.upper()}] {name}\n"
        f"// Generated by smart-contract-generator\n"
        f"// TODO: implement {contract_type} logic\n"
        f"contract {name} {{\n"
        f"    // constructor and methods go here\n"
        f"}}\n"
    )
